pop up
swecc-uw/swecc-client pull request #51
Opened 2024-11-18 00:27 UTC by kipiiler

Author: Hoang Nguyen

## What changes were made?
Made a confirmation pop-up before pairing & listing signup pool status

## Why are these changes important/necessary?

## (If applicable) Screenshots of your changes. Providing an “old vs. new” comparison would be great!

2024-11-18 00:47 UTC, elimelt commented on src/types.ts
> +export interface InterviewStatus {
InterviewSignupStatus or InterviewPoolStatus instead

2024-11-18 00:48 UTC, elimelt reviewed
LGTM besides comment, might get confusing

2024-11-19 02:35 UTC, ShawnCollinge requested changes

2024-11-19 02:35 UTC, ShawnCollinge commented on src/components/debug/PairingDashboard.tsx
> +        console.log(res.data);
Let's not have console.logs in prod please

2024-11-19 02:35 UTC, ShawnCollinge commented on src/components/debug/PairingDashboard.tsx
> +        console.log(error);
No console.log please.

2024-11-19 02:35 UTC, ShawnCollinge commented on src/components/debug/PairingDashboard.tsx
> +    number_sign_up: 0,
camelCase

2024-11-23 22:54 UTC, ShawnCollinge commented on src/components/debug/PairingDashboard.tsx
> +    numberSignUp: 0,
You don't need to set this to 0 as you're already checking below if it's undefined and returning 0 if it is.

2024-11-23 22:54 UTC, ShawnCollinge commented on src/services/api.ts
> +  if (!api.defaults.headers.common["X-CSRFToken"]) {
Please rerun the correct linter on these files.

2024-11-23 22:54 UTC, ShawnCollinge commented on src/services/interview.ts
> +  } as InterviewPoolStatus;
Why are we casting here?

2024-11-23 22:54 UTC, ShawnCollinge commented on src/services/interview.ts
> +  data: RawInterViewPoolStatus
Let's use the same format we've used elsewhere for serializing and deserializing.

2024-11-25 02:01 UTC, elimelt approved these changes
LGTM

2024-11-25 02:02 UTC, merged